version: "3.5"

services:
  pasta:
    image: blakev/pasta:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: "gunicorn --config /app/.gunicorn pasta.app:api"
    environment:
      - PASTA_CONFIG=/app/pasta.config.toml
      - PASTA_DATA=/data
      - GUNICORN_DEBUG=0
      - GUNICORN_RELOAD=1
      - GUNICORN_CONNECTIONS=512
      - GUNICORN_TIMEOUT=60
      - GUNICORN_KEEP_ALIVE=5
      - GUNICORN_WORKERS=2
    volumes:
      - "pasta-data:/data"
    restart: on-failure

volumes:
  pasta-data: