# all the pastes/data go here
data_folder='/home/blake/code/github/pasta/data'
data_folder_sharding=false

# file/data encoding; needs to be consistent
encoding='latin1'

# exclude these characters from the ASCII alphabet
uuids_do_not_include="0OQl1I"

# pregenerate this many uuids at a time
uuids_pregen=1024

# fixed-length of the filenames on disk and uri via HTTP
uuids_size=8

[redis]
    host="localhost"
    port=6379
    db=0

[encryption]
    # 16 or 32 byte secret (password) for encrypting disk data
    secret="changemechangeme"

[pastes]
    max_size=64000
    # allow the user this many seconds to keep the edit page
    # open before their token expires in the database;
    uuid_expires_in=900

[flask]
    DEBUG=true
    TESTING=false
    SECRET_KEY='please-remember-to-change-this-value'
    SESSION_COOKIE_NAME='pasta'
